### PR TITLE
**Window > Preferences > General > Workspaces** has become **Eclipse > Preferences > General > Workspaces**

### PR DESCRIPTION
**Pull request by ruslan-ardashev**

### CODE REVIEW

**Comment by maxbridges** [comment]
I still see Window > Preferences (etc.) in the latest stable release of Eclipse. Is this an upcoming change?

**Comment by ruslan-ardashev** [comment]
ohh. it's probably a windows vs. Mac thing then. I'll make the appropriate
revisions (to the revisions) in a bit

On Thursday, August 6, 2015, Max Bridges notifications@github.com wrote:

> I still see Window > Preferences (etc.) in the latest stable release of
> Eclipse. Is this an upcoming change?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IBM-Bluemix/DevOps-Services-Docs/pull/23#issuecomment-128367754
> .

## 

Ruslan Ardashev

Personal Website http://www.ruslanardashev.com/
Facebook http://www.facebook.com/ruslan.ardashev
LinkedIn http://www.linkedin.com/in/ruslanArdashev/
Personal #: (_631) 839-1117_

Pratt School of Engineering, Duke University Class of 2015
Founder of iFixTeam

**Comment by maxbridges** [comment]
Thanks!

**Comment by ruslan-ardashev** [comment]
How does https://github.com/ruslan120101/DevOps-Services-Docs/commit/da8c4c0dbf50189fc96005a173faf0369a6fa59c look

**Comment by maxbridges** [comment]
I'm not sure on the best way to phrase this--let me pass this on to our editor. Thanks!

**Comment by lwhinson** [comment]
Hey Max - here's a suggested edit:
1. In Eclipse, open the UTF-8 workspace.
   -If you use a Mac, click **Eclipse > Preferences > General > Workspace**. In the "Text file encoding" section, click **Other**, and from the list, select **UTF-8**.
   -If you use a Windows system, click Window > Preferences > General > Workspace**. In the "Text file encoding" section, click Other, and from the list, select **UTF-8**.

**Comment by maxbridges** [comment]
Thanks! I wasn't sure if splitting it up was cool or not. 

Fixed bolding version:
1. In Eclipse, open the UTF-8 workspace.
-If you use a Mac, click **Eclipse > Preferences > General > Workspace**. In the "Text file encoding" section, click **Other**, and from the list, select **UTF-8**.
-If you use a Windows system, click **Window > Preferences > General > Workspace**. In the "Text file encoding" section, click **Other**, and from the list, select **UTF-8**.

**Comment by ruslan-ardashev** [comment]
oof, you're right, it does sound better :)

lemme know if you'd like me to merge / close the pull request!

On Friday, August 7, 2015, Max Bridges notifications@github.com wrote:

> Thanks! I wasn't sure if splitting it up was cool or not.
> 
> Fixed bolding version:
> 1. In Eclipse, open the UTF-8 workspace.
> -If you use a Mac, click _Eclipse > Preferences > General > Workspace_.
> In the "Text file encoding" section, click _Other_, and from the list,
> select _UTF-8_.
> -If you use a Windows system, click _Window > Preferences > General >
> Workspace_. In the "Text file encoding" section, click _Other_, and from
> the list, select _UTF-8_.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IBM-Bluemix/DevOps-Services-Docs/pull/23#issuecomment-128807565
> .

## 

Ruslan Ardashev

Personal Website http://www.ruslanardashev.com/
Facebook http://www.facebook.com/ruslan.ardashev
LinkedIn http://www.linkedin.com/in/ruslanArdashev/
Personal #: (_631) 839-1117_

Pratt School of Engineering, Duke University Class of 2015
Founder of iFixTeam

**Comment by maxbridges** [comment]
If you'd like to make the update, that's cool. Otherwise, close and I'll update it myself.

**Comment by ruslan-ardashev** [comment]
#IBelieveInMax

On Friday, August 7, 2015, Max Bridges notifications@github.com wrote:

> If you'd like to make the update, that's cool. Otherwise, close and I'll
> update it myself.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IBM-Bluemix/DevOps-Services-Docs/pull/23#issuecomment-128823095
> .

## 

Ruslan Ardashev

Personal Website http://www.ruslanardashev.com/
Facebook http://www.facebook.com/ruslan.ardashev
LinkedIn http://www.linkedin.com/in/ruslanArdashev/
Personal #: (_631) 839-1117_

Pratt School of Engineering, Duke University Class of 2015
Founder of iFixTeam

**Comment by maxbridges** [comment]
Done! Thanks!

**Comment by ruslan-ardashev** [comment]
*high fives all around *

teamwork

On Friday, August 7, 2015, Max Bridges notifications@github.com wrote:

> Done!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IBM-Bluemix/DevOps-Services-Docs/pull/23#issuecomment-128828114
> .

## 

Ruslan Ardashev

Personal Website http://www.ruslanardashev.com/
Facebook http://www.facebook.com/ruslan.ardashev
LinkedIn http://www.linkedin.com/in/ruslanArdashev/
Personal #: (_631) 839-1117_

Pratt School of Engineering, Duke University Class of 2015
Founder of iFixTeam

**Comment by maxbridges** [comment]
#DreamBigOrGoHome

**Comment by ruslan-ardashev** [comment]
#tooFarToStopTooProudToFail

On Friday, August 7, 2015, Max Bridges notifications@github.com wrote:

> #DreamBigOrGoHome
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IBM-Bluemix/DevOps-Services-Docs/pull/23#issuecomment-128831514
> .

## 

Ruslan Ardashev

Personal Website http://www.ruslanardashev.com/
Facebook http://www.facebook.com/ruslan.ardashev
LinkedIn http://www.linkedin.com/in/ruslanArdashev/
Personal #: (_631) 839-1117_

Pratt School of Engineering, Duke University Class of 2015
Founder of iFixTeam

**Pull request closed without merging**
